variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "fetch"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GET_SOURCES_ATTEMPTS: "10"

default:
  before_script:
    - dnf install -y gcc gcc-c++ gcc-gfortran openblas openblas-devel lapack lapack-devel
                     mpich mpich-devel openmpi openmpi-devel hdf5 hdf5-devel git make cmake
                     python python3 python3-pip python3-h5py redhat-rpm-config findutils
                     which procps-ng coreutils environment-modules
    - . ~/.bashrc
    - . /etc/profile.d/modules.sh
    - module purge
    - module avail
    - uname -a
    - lscpu
    - free -h
    - gfortran --version
    - gcc --version
    - g++ --version
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - module purge
    - module load mpi/mpich-x86_64
    - mpirun --version
    - module purge
    - python3 --version
    - git --version
    - cmake --version

coverage:
  image: fedora:37
  tags:
    - saas-linux-2xlarge-amd64
  coverage: '/Percentage Coverage:\s*([^%]+)/'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q gcovr
    - module load mpi/mpich-x86_64
    - mpirun --version
    - pip install -q codecov
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release --coverage
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - export DALTON_LAUNCHER="mpirun -n 4"
    - export OMP_NUM_THREADS=1
    - ctest -j 4 --output-on-failure -L dalton -LE "serial|long|verylong"
    - export DALTON_LAUNCHER=""
    - export OMP_NUM_THREADS=1
    - ctest -j 16 --output-on-failure -L serial -LE "long|verylong"
    - ctest -D ExperimentalCoverage
  interruptible: true

intel-oneapi-2024.2.1:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  before_script:
    - mv maintenance/oneAPI.repo /etc/yum.repos.d/oneAPI.repo
    - dnf install -y gcc gcc-c++ gcc-gfortran git make cmake
                     python python3 python3-pip redhat-rpm-config findutils
                     which procps-ng coreutils environment-modules
                     intel-oneapi-compiler-dpcpp-cpp-2024.2.1-1079
                     intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.1-16
                     intel-oneapi-compiler-fortran-2024.2.1-1079
                     intel-oneapi-mkl-2024.2.1-103 intel-oneapi-mkl-devel-2024.2.1-103
    - . /etc/profile.d/modules.sh
    - /opt/intel/oneapi/modulefiles-setup.sh --ignore-latest --output-dir=~/intel-oneapi-modulefiles --force
    - module use ~/intel-oneapi-modulefiles
    - module purge
    - module load tbb/2021.13 compiler-rt/2024.2.1 compiler/2024.2.1 mkl/2024.2 oclfpga/2023.2.1
    - uname -a
    - lscpu
    - free -h
    - ifx --version
    - icx --version
    - icpx --version
    - python3 --version
    - git --version
    - cmake --version
  script:
    - python setup --fc=ifx --cc=icx --cxx=icpx --mkl=sequential --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --output-on-failure -L serial -LE "long|verylong"
  interruptible: true

intel-oneapi-mpi:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  before_script:
    - mv maintenance/oneAPI.repo /etc/yum.repos.d/oneAPI.repo
    - dnf install -y gcc gcc-c++ gcc-gfortran git make cmake
                     python python3 python3-pip redhat-rpm-config findutils
                     which procps-ng coreutils environment-modules
                     intel-oneapi-compiler-dpcpp-cpp
                     intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
                     intel-oneapi-compiler-fortran
                     intel-oneapi-mkl intel-oneapi-mkl-devel
                     intel-oneapi-mpi intel-oneapi-mpi-devel
    - . /etc/profile.d/modules.sh
    - /opt/intel/oneapi/modulefiles-setup.sh --ignore-latest --output-dir=~/intel-oneapi-modulefiles --force
    - module use ~/intel-oneapi-modulefiles
    - module purge
    - module load tbb/2021.13 compiler-rt/2024.2.1 compiler/2024.2.1 mkl/2024.2 oclfpga/2023.2.1 mpi
    - uname -a
    - lscpu
    - free -h
    - ifx --version
    - icx --version
    - icpx --version
    - mpirun --version
    - python3 --version
    - git --version
    - cmake --version
  script:
    - python setup --fc=mpiifx --cc=mpiicx --cxx=mpiicpx --mkl=sequential --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --output-on-failure -L dalton -LE "serial|long|verylong"
  interruptible: true

intel-classic-2024-2.1:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  before_script:
    - mv maintenance/oneAPI.repo /etc/yum.repos.d/oneAPI.repo
    - dnf install -y gcc gcc-c++ gcc-gfortran git make cmake
                     python python3 python3-pip redhat-rpm-config findutils
                     which procps-ng coreutils environment-modules
                     intel-oneapi-compiler-dpcpp-cpp-2024.2.1-1079
                     intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.1-16
                     intel-oneapi-compiler-fortran-2024.2.1-1079
                     intel-oneapi-mkl-2024.2.1-103 intel-oneapi-mkl-devel-2024.2.1-103
    - . /etc/profile.d/modules.sh
    - /opt/intel/oneapi/modulefiles-setup.sh --ignore-latest --output-dir=~/intel-oneapi-modulefiles --force
    - module use ~/intel-oneapi-modulefiles
    - module purge
    - module load tbb/2021.13 compiler-rt/2024.2.1 compiler/2024.2.1 mkl/2024.2 oclfpga/2023.2.1
    - uname -a
    - lscpu
    - free -h
    - ifx --version
    - icx --version
    - icpx --version
    - python3 --version
    - git --version
    - cmake --version
  script:
    - python setup --fc=ifx --cc=icx --cxx=icpx --mkl=sequential --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

intel-classic-mpi:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  before_script:
    - mv maintenance/oneAPI.repo /etc/yum.repos.d/oneAPI.repo
    - dnf install -y gcc gcc-c++ gcc-gfortran git make cmake
                     python python3 python3-pip redhat-rpm-config findutils
                     which procps-ng coreutils environment-modules
                     intel-oneapi-compiler-dpcpp-cpp
                     intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
                     intel-oneapi-compiler-fortran
                     intel-oneapi-mkl intel-oneapi-mkl-devel
                     intel-oneapi-mpi intel-oneapi-mpi-devel
    - . /etc/profile.d/modules.sh
    - /opt/intel/oneapi/modulefiles-setup.sh --ignore-latest --output-dir=~/intel-oneapi-modulefiles --force
    - module use ~/intel-oneapi-modulefiles
    - module purge
    - module load compiler-rt/2024.2.1 compiler/2024.2.1 mpi mkl/2024.2
    - uname -a
    - lscpu
    - free -h
    - ix --version
    - icx --version
    - icpx --version
    - mpirun --version
    - python3 --version
    - git --version
    - cmake --version
  script:
    - python setup --fc=mpiifort --cc=mpiicc --cxx=mpiicpc --mkl=sequential --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-5:
  image: fedora:23
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --output-on-failure -L essential -E rsp_mnf
  interruptible: true

gcc-5-int64:
  image: fedora:23
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=builtin --explicit-libs="-lopenblas64" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential -E rsp_mnf
  interruptible: true

gcc-6:
  image: fedora:25
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential -E rsp_mnf
  interruptible: true

gcc-6-int64:
  image: fedora:25
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=builtin --explicit-libs="-lopenblas64" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential -E rsp_mnf
  interruptible: true

gcc-7:
  image: fedora:27
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-7-int64:
  image: fedora:27
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-8:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-8-int64:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-8-ompi-2.1:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-8-ompi-2.1-int64:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-9:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-9-int64:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-9-ompi-4.0:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-9-mpich-3.3:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/mpich-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-9-ompi-4.0-int64:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-9-mpich-3.3-int64:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - module load mpi/mpich-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial --timeout 30
  interruptible: true

gcc-10:
  image: fedora:32
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-10-int64:
  image: fedora:32
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-11:
  image: fedora:35
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-11-int64:
  image: fedora:35
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-11-mpich-3.4:
  image: fedora:35
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/mpich-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-11-mpich-3.4-int64:
  image: fedora:35
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  script:
    - dnf install -y -q lapack64
    - module load mpi/mpich-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial --timeout 30
  interruptible: true

gcc-12:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-12-debug:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=debug
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-12-int64:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - when: always
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j 32
    - ctest -j 16 --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-12-ompi-4.1:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-12-mpich-4.0:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/mpich-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-12-ompi-4.1-int64:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-12-mpich-4.0-int64:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  allow_failure: true
  script:
    - dnf install -y -q lapack64
    - module load mpi/mpich-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial --timeout 30
  interruptible: true

nightly-gcc-serial:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  tags:
    - parallel
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedules'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
  allow_failure: true
  script:
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON -DSITE=GitLab -DBUILDNAME=$CI_COMMIT_REF_NAME-gcc-serial
    - cd build
    - export CTEST_MAKE_NUM_PROCS=4
    - ctest -j 4 --output-on-failure -L dalton -M Nightly -T Build -T Test -T Submit

nightly-gcc-mpi:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - parallel
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedules'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
  allow_failure: true
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON -DSITE=GitLab -DBUILDNAME=$CI_COMMIT_REF_NAME-gcc-mpi
    - cd build
    - export CTEST_MAKE_NUM_PROCS=4
    - ctest --output-on-failure -L dalton -M Nightly -T Build -T Test -T Submit

nightly-gcc-mpi-int64:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - parallel
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedules'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
  allow_failure: true
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
                   -DSITE=GitLab -DBUILDNAME=$CI_COMMIT_REF_NAME-gcc-mpi-int64
    - cd build
    - export CTEST_MAKE_NUM_PROCS=4
    - ctest --output-on-failure -L dalton -M Nightly -T Build -T Test -T Submit

nightly-intel:
  image: fedora:32
  variables:
    DALTON_LAUNCHER: "mpirun -n 4"
    OMP_NUM_THREADS: "1"
  tags:
    - parallel
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedules'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
  allow_failure: true
  before_script:
    - dnf upgrade -y -q
    - dnf install -y -q gcc gcc-c++ gcc-gfortran git make cmake python python3
                        redhat-rpm-config findutils which procps-ng coreutils
    - mv maintenance/oneAPI.repo /etc/yum.repos.d
    - dnf install -y intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mkl intel-oneapi-mpi intel-oneapi-mpi-devel
    - set +e
    - . /opt/intel/inteloneapi/setvars.sh
    - set -e
    - uname -a
    - lscpu
    - free -h
    - ifx --version
    - icc --version
    - icpc --version
    - mpirun --version
    - python3 --version
    - git --version
    - cmake --version
  script:
    - python setup --fc=mpiifx --cc=mpiicc --cxx=mpiicpc --mpi --mkl=sequential --type=release
                   -DSITE=GitLab -DBUILDNAME=$CI_COMMIT_REF_NAME-intel-mpi
    - cd build
    - export CTEST_MAKE_NUM_PROCS=4
    - ctest --output-on-failure -L dalton -M Nightly -T Build -T Test -T Submit
