workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
      variables:
        RUNNER_TAG: "saas-linux-2xlarge-amd64"
    - if: $CI_PROJECT_NAMESPACE != "dalton"
      variables:
        RUNNER_TAG: "saas-linux-medium-amd64"

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "fetch"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GET_SOURCES_ATTEMPTS: "10"

include:
  - local: /.gitlab-ci/.functions.yml
  - local: /.gitlab-ci/.serial.yml
  - local: /.gitlab-ci/.openmpi.yml
  - local: /.gitlab-ci/.mpich.yml
  - local: /.gitlab-ci/.intel.yml
  - local: /.gitlab-ci/.coverage.yml
  - local: /.gitlab-ci/.nightly.yml

default:
  before_script:
    - dnf install -y gcc gcc-c++ gcc-gfortran openblas openblas-devel lapack lapack-devel
                     mpich mpich-devel openmpi openmpi-devel hdf5 hdf5-devel git make cmake
                     python python3 python3-pip python3-h5py redhat-rpm-config findutils
                     which procps-ng coreutils environment-modules
    - . ~/.bashrc
    - . /etc/profile.d/modules.sh
    - module purge
    - module avail
    - uname -a
    - lscpu
    - free -h
    - gfortran --version
    - gcc --version
    - g++ --version
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - module purge
    - module load mpi/mpich-x86_64
    - mpirun --version
    - module purge
    - python3 --version
    - git --version
    - cmake --version
  tags:
    - $RUNNER_TAG
  artifacts:
    when: on_failure
    paths:
      - build/test*