.define-cores:
  script:
    - cores=$(LC_ALL=C lscpu | awk '/^Core\(s\) per socket:/ {print $4}')
    - sockets=$(LC_ALL=C lscpu | awk '/^Socket\(s\):/ {print $2}')
    - N_PROC=$((cores * sockets))
    - |
      if [ "$N_PROC" -lt 4 ]; then
        M=$((N_PROC / 2))
        export NEW_DALTON_LAUNCHER="mpirun -n 2"
      else
        M=$((N_PROC / 4))
        export NEW_DALTON_LAUNCHER="mpirun -n 4"
      fi
      if [[ -v DALTON_LAUNCHER ]]; then
        echo "DALTON_LAUNCHER defined by the build."
      else
        echo "DALTON_LAUNCHER defined by define-cores function."
        echo "DALTON_LAUNCHER=\"$NEW_DALTON_LAUNCHER\"" > var_cores.env
      fi
      echo "N_PROC=$N_PROC" >> var_cores.env
      echo "M=$M" >> var_cores.env
    - source var_cores.env
    - export DALTON_LAUNCHER=$DALTON_LAUNCHER
    - echo "The total number of physical cores is $N_PROC"
    - echo "DALTON_LAUNCHER was set to $DALTON_LAUNCHER"