intel-oneapi-serial:
  image: fedora:40
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  allow_failure: true
  before_script:
    # Update system and install necessary packages
    - dnf -y update
    - dnf -y install git python python3 python3-pip wget pkg-config ca-certificates gnupg cmake environment-modules
    # Download Intel GPG key
    - wget https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
    # Import Intel GPG key
    - rpm --import GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
    # Add Intel oneAPI repository
    - echo -e "[oneAPI]\nname=Intel(R) oneAPI repository\nbaseurl=https://yum.repos.intel.com/oneapi\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" | sudo tee /etc/yum.repos.d/oneAPI.repo
    # Install Intel oneAPI packages
    - dnf -y update
    - dnf -y install intel-oneapi-compiler-dpcpp-cpp intel-oneapi-compiler-fortran intel-oneapi-mkl intel-oneapi-mpi intel-oneapi-mpi-devel
    # Set up environment for Intel oneAPI
    - . /etc/profile.d/modules.sh
    - /opt/intel/oneapi/modulefiles-setup.sh --ignore-latest --output-dir=~/intel-oneapi-modulefiles --force
    - module use ~/intel-oneapi-modulefiles
    - module purge
    - echo "=== Available modules ==="
    - module avail
    - module load tbb/2022.2 compiler-rt/2025.2.0 compiler/2025.2.0 mkl/2025.2 mpi
    # Print useful info
    - uname -a
    - lscpu
    - free -h
    - ifx --version
    - icx --version
    - icpx --version
    - mpirun --version
    - echo "MKLROOT=$MKLROOT"
    - python3 --version
    - git --version
    - cmake --version
  script:
    - !reference [.define-cores, script]
    - ulimit -s unlimited
    - echo "The shell is $SHELL"
    - python setup --fc=ifx --cc=icx --cxx=icpx --mkl=sequential --type=release
    - cd build
    - make -j $N_PROC
    - ldd dalton.x
    - echo "Running ctest with $N_PROC jobs"
    - ctest -j$N_PROC --output-on-failure -L "serial|essential" -LE "long|verylong" -E cc_rsp_alpha
  artifacts:
    when: always
    paths:
      - build/test/
    expire_in: 3 days
  interruptible: true

intel-oneapi-mpi:
  image: fedora:40
  variables:
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  allow_failure: true
  before_script:
    # Update system and install necessary packages
    - dnf -y update
    - dnf -y install git python python3 python3-pip wget pkg-config ca-certificates gnupg cmake environment-modules
    # Download Intel GPG key
    - wget https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
    # Import Intel GPG key
    - rpm --import GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
    # Add Intel oneAPI repository
    - echo -e "[oneAPI]\nname=Intel(R) oneAPI repository\nbaseurl=https://yum.repos.intel.com/oneapi\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" | sudo tee /etc/yum.repos.d/oneAPI.repo
    # Install Intel oneAPI packages
    - dnf -y update
    - dnf -y install intel-oneapi-compiler-dpcpp-cpp intel-oneapi-compiler-fortran intel-oneapi-mkl intel-oneapi-mpi intel-oneapi-mpi-devel
    # Set up environment for Intel oneAPI
    - . /etc/profile.d/modules.sh
    - /opt/intel/oneapi/modulefiles-setup.sh --ignore-latest --output-dir=~/intel-oneapi-modulefiles --force
    - module use ~/intel-oneapi-modulefiles
    - module purge
    - echo "=== Available modules ==="
    - module avail
    - module load tbb/2022.2 compiler-rt/2025.2.0 compiler/2025.2.0 mkl/2025.2 mpi/2021.16
    # Print useful info
    - uname -a
    - lscpu
    - free -h
    - mpiifx --version
    - mpiicx --version
    - mpiicpx --version
    - mpirun --version
    - echo "MKLROOT=$MKLROOT"
    - python3 --version
    - git --version
    - cmake --version
  script:
    - !reference [.define-cores, script]
    - ulimit -s unlimited
    - echo "The shell is $SHELL"
    - python setup --fc=mpiifx --cc=mpiicx --cxx=mpiicpx --mkl=sequential --type=release
    - cd build
    - make -j $N_PROC
    - ldd dalton.x
    - export I_MPI_SHM_HEAP_VSIZE=0
    - export I_MPI_SHM=disable
    - echo "Running ctest with $M jobs"
    - ctest -j$M --output-on-failure -L dalton -LE "serial|long|verylong"
  artifacts:
    when: always
    paths:
      - build/test/
    expire_in: 3 days
  interruptible: true
