gcc-8-ompi-2.1:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true

gcc-8-ompi-2.1-int64:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true
  
gcc-9-ompi-4.0:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true
  
gcc-9-ompi-4.0-int64:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64 lapack64-devel
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true
  
gcc-12-ompi-4.1:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --mpi --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true
  
gcc-12-ompi-4.1-int64:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: "mpirun -n 4 --allow-run-as-root --oversubscribe --bind-to none"
    OMP_NUM_THREADS: "1"
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_PROJECT_NAMESPACE == 'dalton'
    - if: $CI_PIPELINE_SOURCE == 'schedules'
      when: never
  script:
    - dnf install -y -q lapack64
    - module load mpi/openmpi-x86_64
    - mpirun --version
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --mpi --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j 32
    - ctest -j 4 --timeout 120 --output-on-failure -L essential -LE serial
  interruptible: true
