gcc-6:
  image: fedora:25
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential -E rsp_mnf
  interruptible: true

gcc-6-int64:
  image: fedora:25
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=builtin --explicit-libs="-lopenblas64" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential -E rsp_mnf
  interruptible: true

gcc-7:
  image: fedora:27
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-7-int64:
  image: fedora:27
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-8:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-8-int64:
  image: fedora:29
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64 lapack64-devel
    - alternatives --install /usr/bin/python python /usr/bin/python3 1
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-9:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-9-int64:
  image: fedora:31
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64 lapack64-devel
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-10:
  image: fedora:32
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-10-int64:
  image: fedora:32
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64 lapack64-devel
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64_" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-11:
  image: fedora:35
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-11-int64:
  image: fedora:35
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-12:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=release
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-12-debug:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --blas=none --lapack=none --explicit-libs="-lopenblas -llapack" --type=debug
                   -DENABLE_PDE=ON
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true

gcc-12-int64:
  image: fedora:37
  variables:
    DALTON_LAUNCHER: ""
    OMP_NUM_THREADS: "1"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_PIPELINE_SOURCE != 'schedules'
      when: manual
  script:
    - !reference [.define-cores, script]
    - dnf install -y -q lapack64
    - export FFLAGS="-I/usr/lib64/gfortran/modules"
    - python setup --int64 --blas=none --lapack=none --explicit-libs="-lopenblas64 -llapack64" --type=release
    - cd build
    - make -j $N_PROC
    - ctest -j $N_PROC --timeout 120 --output-on-failure -L essential
  interruptible: true
