#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'molecule density',
      num_lines = 100,
      abs_tolerance = 1.0e-5)

test.run(['cubetest.dal'], ['h2o-dz.mol'], f={'density.cube': f}, args='-get "density.cube"')

sys.exit(test.return_code)
