#!/usr/bin/env python
#    energy_nosymm
#    -------------
#    Molecule:         H2O
#    Wave Functions:   SCF, MP2, and MCSCF (CAS) / cc-pVDZ (Atombasis)
#    Test Purpose:     Check MCSCF energy calculation without symmetry

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'Cartesian Coordinates',
      num_lines = 8,
      rel_tolerance = 1.0e-8)

f.add(string = 'Nuclear repulsion energy',
      rel_tolerance = 1.0e-10)

f.add(from_string = 'Wave function specification',
      num_lines = 20)

f.add(re = 'Hartree-Fock .*total energy',
      rel_tolerance = 1.0e-9)
f.add(string = 'MP2 second order energy',
      rel_tolerance = 1.0e-9)
f.add(string = 'Final MCSCF energy:',
      rel_tolerance = 1.0e-9)

f.add(from_string = 'Occupancies of natural orbitals',
      to_string = 'Head-Gordon',
      abs_tolerance = 1.0e-5)

test.run(['energy_nosymm.dal'], ['H2O_cc-pVDZ.mol'], f={'out': f})

sys.exit(test.return_code)
