#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(string = 'Nuclear repulsion energy',
      rel_tolerance = 1.0e-10)

f.add(from_string = 'Wave function specification',
      to_string = 'Total number of variables',
      rel_tolerance = 1.e-10)

f.add(string = 'Number of coordinates in each symmetry')
f.add(string = 'Number of orbitals in each symmetry')

f.add(string = 'Hartree-Fock total energy',
      rel_tolerance = 1.0e-8)
f.add(string = 'Final MC-SRDFT energy:',
      rel_tolerance = 1.0e-8)

f.add(from_string = 'KT ionization potentials [eV] and pole strengths',
      to_string = 'KT output',
      rel_tolerance = 1.e-4)

#f.add(from_string = 'Occupancies of natural orbitals',
#      num_lines = 16, ignore_order = True,
#      abs_tolerance = 1.0e-5)


test.run(['energy_srlda_openshell_EKT.dal'], ['H2O.mol'], f={'out': f})

sys.exit(test.return_code)
