#!/usr/bin/env python
#    prop_lresc
#    -------------
#    Molecule:         FH
#    Wave Function:    Hartree Fock
#    Test Purpose:     LRESC correction to Fluorine Shielding constant

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

simple = Filter()

simple.add(from_string = 'Atoms and basis sets',
      num_lines = 15,
      rel_tolerance = 1.0e-2)

simple.add(from_string = 'Cartesian Coordinates',
      num_lines = 7,
      rel_tolerance = 1.0e-8)

simple.add(from_string = 'Total Non-relativistic Contributions for F',
      num_lines = 26,
      abs_tolerance = 1.0e-3)


detailed = Filter()

detailed.add(from_string = 'Atoms and basis sets',
      num_lines = 15,
      rel_tolerance = 1.0e-2)

detailed.add(from_string = 'Cartesian Coordinates',
      num_lines = 7,
      rel_tolerance = 1.0e-8)

detailed.add(from_string = 'Paramagnetic Corrections for F',
      num_lines = 75,
      abs_tolerance = 1.0e-3)
      
detailed.add(from_string = 'Diamagnetic Corrections for F',
      num_lines = 43,
      abs_tolerance = 1.0e-3)
      
detailed.add(from_string = 'Total Non-relativistic Contributions for F',
      num_lines = 38,
      abs_tolerance = 1.0e-3)

detailed.add(from_string = 'Total Relativistic Corrections for F',
      num_lines = 38,
      abs_tolerance = 1.0e-3)

detailed.add(from_string = 'Total Relativistic Values for F',
      num_lines = 38,
      abs_tolerance = 1.0e-3)

detailed.add(from_string = 'Anisotropic parameters:',
      num_lines = 5,
      abs_tolerance = 1.0e-3)

test.run(['prop_lresc.dal'], ['HF_intgrl.mol'], f={'out': simple})
test.run(['prop_lresc_detailed.dal'], ['HF_intgrl.mol'], f={'out': detailed})

sys.exit(test.return_code)
